### ISSUE TITLE
base_testcriteriatool tqdm set_description to print the test case name with progress togetherwq

### ISSUE THREAD

**Issue by Marvinmw** [thierry-tct/muteria#2]
`# Execute each test and gather the data
  processbar = tqdm.tqdm(testcases, leave=False, dynamic_ncols=True)
  for testcase in processbar:
        processbar.set_description("Run Test %s"% testcase)
`

**Comment by thierry-tct** [comment]
processbar = tqdm.tqdm(testcases, leave=False, dynamic_ncols=True) 
for testcase in processbar: 
    processbar.set_description("Run Test %s"% testcase)
